### ISSUE TITLE
Chronicle doesn't install on Node 0.12

### ISSUE THREAD

**Issue by pdehaan** [mozilla/chronicle#321]
**TL;DR:** Don't install Node 0.12 yet.

---

I installed [**nvm**](https://github.com/creationix/nvm) and gave [Node 0.12](https://github.com/joyent/node/releases/tag/v0.12.0) a try, but it fails [hard] with the following spew:

```sh
> node-sass@1.2.3 install /Users/pdehaan/dev/tmp/chron12/chronicle/node_modules/grunt-sass/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /Users/pdehaan/dev/tmp/chron12/chronicle/node_modules/grunt-sass/node_modules/node-sass/vendor/darwin-x64/binding.node

> node-sass@1.2.3 postinstall /Users/pdehaan/dev/tmp/chron12/chronicle/node_modules/grunt-sass/node_modules/node-sass
> node scripts/build.js

`darwin-x64` exists; testing
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/pdehaan/dev/tmp/chron12/chronicle/node_modules/grunt-sass/node_modules/node-sass/lib/index.js:181:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

> intern@2.2.2 install /Users/pdehaan/dev/tmp/chron12/chronicle/node_modules/intern
> node support/fixdeps.js

npm ERR! Darwin 14.1.0
npm ERR! argv "/usr/local/opt/nvm/versions/node/v0.12.0/bin/node" "/usr/local/opt/nvm/versions/node/v0.12.0/bin/npm" "i"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! node-sass@1.2.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@1.2.3 postinstall script 'node scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/pdehaan/dev/tmp/chron12/chronicle/npm-debug.log
```

Looks like a **node-sass** issue (see https://github.com/sass/node-sass/issues/653) which should hopefully be fixed in **node-sass@2.0.0**, but not sure if there is an [ETA](https://github.com/sass/node-sass/issues/602) yet.

**Comment by pdehaan** [comment]
No real big shocker, but I get similar errors w/ **io.js@1.1.0**:

```sh
npm ERR! Darwin 14.1.0
npm ERR! argv "/usr/local/opt/nvm/versions/io.js/v1.1.0/bin/iojs" "/usr/local/opt/nvm/versions/io.js/v1.1.0/bin/npm" "i"
npm ERR! node v1.1.0
npm ERR! npm  v2.4.1
npm ERR! code ELIFECYCLE

npm ERR! node-sass@1.2.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@1.2.3 postinstall script 'node scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/pdehaan/dev/tmp/chron12/chronicle/npm-debug.log
```

Where:
```sh
$ node -v # v1.1.0
$ npm -v # 2.4.1
$ iojs -v # v1.1.0
```

**Comment by pdehaan** [comment]
![](http://cdn2.business2community.com/wp-content/uploads/2014/05/attention-economy-zoidberg-why.png)

**Comment by pdehaan** [comment]
This may be fixed w/ newer versions of **grunt-sass**.
```sh
$ npm run outdated

> mozilla-chronicle@0.1.0 outdated /Users/pdehaan/dev/github/chronicle
> npm outdated --depth 0

Package     Current  Wanted  Latest  Location
grunt-sass   0.17.0  0.17.0  0.18.0  grunt-sass

$ changelog grunt-sass
0.18.0 / 2015-02-13
  * 0.18.0
  * node-sass 2.0 compatibility
  * Close https://github.com/sindresorhus/grunt-sass/issues/179 PR: Update the sass task for node-sass 2.0.0.
  * Update .travis.yml
  * Update readme.md
  * add link to http://sass-compatibility.github.io
```
