### ISSUE TITLE
Server Error: Unauthorized

### ISSUE THREAD

**Issue by nchapman** [mozilla/chronicle#65]
I get this error in the log every time I load the root path (<http://localhost:8080/>). I assume this is a temporary problem until we finish setting up auth.

```
Debug: auth, unauthenticated, error, session
    Error: Unauthorized
    at Object.exports.create (/Users/nchapman/Code/chronicle/node_modules/hapi-auth-cookie/node_modules/boom/lib/index.js:21:17)
    at Object.exports.unauthorized (/Users/nchapman/Code/chronicle/node_modules/hapi-auth-cookie/node_modules/boom/lib/index.js:85:23)
    at validate (/Users/nchapman/Code/chronicle/node_modules/hapi-auth-cookie/lib/index.js:114:49)
    at Object.scheme.authenticate (/Users/nchapman/Code/chronicle/node_modules/hapi-auth-cookie/lib/index.js:179:13)
    at /Users/nchapman/Code/chronicle/node_modules/hapi/lib/auth.js:214:30
    at internals.Protect.run (/Users/nchapman/Code/chronicle/node_modules/hapi/lib/protect.js:56:5)
    at authenticate (/Users/nchapman/Code/chronicle/node_modules/hapi/lib/auth.js:205:26)
    at internals.Auth._authenticate (/Users/nchapman/Code/chronicle/node_modules/hapi/lib/auth.js:328:5)
    at internals.Auth.authenticate (/Users/nchapman/Code/chronicle/node_modules/hapi/lib/auth.js:164:17)
    at /Users/nchapman/Code/chronicle/node_modules/hapi/lib/request.js:321:13
```

**Comment by 6a68** [comment]
This is only really useful for local server debugging; it's a result of [this line](https://github.com/mozilla/chronicle/blob/e2bd288/server/index.js#L13-L14) in server/index.

Maybe, instead of this always being visible for the `local` env, I can set an independent environment variable?
